### ISSUE TITLE
“Make tabs "read" when tab contents are scrolled” doesn't work correctly

### ISSUE THREAD

**Issue by Infocatcher** [piroor/informationaltab#20]
Example:
* open https://addons.mozilla.org/ in background tab, wait for loading (unread style)
* switch to that tab (has scrollbar, but will be marked as read)

(tested with latest Informational Tab 0.5.2014100300a141259 + Firefox 34.0.5)

**Comment by Infocatcher** [comment]
Still doesn't work for me...

**Comment by Vampire** [comment]
same for me. Status is set to read as soon as tab is opened, no matter whether it has a scroll-bar or not

**Comment by piroor** [comment]
I think this has been fixed on the master (but not released yet). Could you try the latest development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Vampire** [comment]
FF doesn't let me install it, because it is not signed

**Comment by piroor** [comment]
Yes, you need to disable the signature check. http://www.ghacks.net/2015/06/19/how-to-disable-the-firefox-40-add-on-signing-requirement/

**Comment by Vampire** [comment]
Hm, I've set the property to false, but it still won't let me install.

**Comment by Infocatcher** [comment]
> http://piro.sakura.ne.jp/xul/xpi/nightly/

Great! Now looks fixed for me, thanks.
